spring:
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog-master.xml

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/internship
    username: user
    password: password
    hikari:
      register-mbeans: true

springdoc:
  packages-to-scan: sigma.internship.petProject.controller
  paths-to-match: /**

access-token:
  private: access-refresh-token-keys/access-token-private.key
  public: access-refresh-token-keys/access-token-public.key
refresh-token:
  private: access-refresh-token-keys/refresh-token-private.key
  public: access-refresh-token-keys/refresh-token-public.key