spring:
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog-master.xml

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/internship
    username: user
    password: password
    hikari:
      register-mbeans: true

springdoc:
  packages-to-scan: software.sigma.internship.controller
  paths-to-match: /**